### PR TITLE
[MISC] add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ziyanx02**
Add CONTRIBUTING.md.

### CODE REVIEW

**Review by YilingQiao — APPROVED** [review]

**Comment by YilingQiao** [comment]
Hi, could you please test if the pre-commit hook is working as expected? I want to set the line width to 120, but it seems to format everything with a smaller value.

**Comment by ziyanx02** [comment]
> Hi, could you please test if the pre-commit hook is working as expected? I want to set the line width to 120, but it seems to format everything with a smaller value.

I will try it tomorrow

**Comment by zswang666** [comment]
Should we add guide for test/check in CI on local machine?
```
black --check .
black . # to auto-format if the above check failed
python -m unittest discover tests
```

**Comment by ziyanx02** [comment]
Seems those CI tests require >6G gpu memory so I will add local tests as optional.

As for auto-reformat, I got 19 files to be reformatted after running `black --check .` XD. That doesn't seem right, does it?

**Comment by ziyanx02** [comment]
> Hi, could you please test if the pre-commit hook is working as expected? I want to set the line width to 120, but it seems to format everything with a smaller value.

I can't find a counter case. An extremely long string or name won't be truncated even longer than 120. Long numerical expressions will be divided into parts as short as possible I guess?

**Comment by ziyanx02** [comment]
The final version is
- using pre-commit to avoid forgetting to check.
- Suggesting to do local CI tests.

**Pull request merged**
