### PR TITLE
Add Pause and reset function on Genesis 

### PR DESCRIPTION
**Pull request by JonnyDing**
---

### Feature Enhancement

To improve the workflow when loading robot models from URDF or XML files, I added a feature to simplify setting default joint positions:

```python
robot.set_dofs_position(default_dof_pos, dofs_idx)
```

This enhancement includes a utility to validate joint positions more conveniently, reducing reliance on manual debugging.

I have implemented this feature and would like to submit a PR for your review. Feedback and suggestions are welcome! 😊

---
微信图片_20241224190352

### CODE REVIEW

**Comment by JonnyDing** [comment]
> `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
No you needn't adjust. If you press Space,the simulation will stop. and if you space Space again ,the simulation will continue to run. If you press x key ,the drone will reset to initial state

**Comment by JonnyDing** [comment]
> `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that

No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.

**Comment by PieterBecking** [comment]
> > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> 
> 
> 
> No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state. 
> 
> 
> 
> 

Yes I do as space bar is thrust for the drone

**Comment by JonnyDing** [comment]
> > > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> > 
> > 
> > No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.
> 
> Yes I do as space bar is thrust for the drone

**Comment by JonnyDing** [comment]
> > > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> > 
> > 
> > No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.
> 
> Yes I do as space bar is thrust for the drone

Emmm I cannot find suitable key for pause function because i choose Space key is more convenient

**Comment by JonnyDing** [comment]
> > > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> > 
> > 
> > No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.
> 
> Yes I do as space bar is thrust for the drone
I'm using the shift button as a thrust. lol

**Comment by PieterBecking** [comment]
> > > > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> 
> > > 
> 
> > > 
> 
> > > No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.
> 
> > 
> 
> > Yes I do as space bar is thrust for the drone
> 
> 
> 
> Emmm I cannot find suitable key for pause function because i choose Space key is more convenient

Yeah no worries I can pick another for the thrust if necessary👍

**Comment by JonnyDing** [comment]
> > > > > `examples/drone/interactive_drone.py` would have to be adjusted if the space bar would be pause. Can do that
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > No adjustment is needed. In the current implementation, pressing the space bar will stop the simulation, and pressing it again will resume. Additionally, the 'x' key resets the drone to its initial state.
> > 
> > 
> > > 
> > 
> > 
> > > Yes I do as space bar is thrust for the drone
> > 
> > 
> > Emmm I cannot find suitable key for pause function because i choose Space key is more convenient
> 
> Yeah no worries I can pick another for the thrust if necessary👍

thanks.my English is not very good。

**Pull request closed without merging**
