### PR TITLE
Interactive drone controlled - cross-platform

### PR DESCRIPTION
**Pull request by PieterBecking**
# Drone Examples

This directory contains examples of drone simulations using the Genesis framework.

### 1. Interactive Drone (`interactive_drone.py`)
A real-time interactive drone simulation where you can control the drone using keyboard inputs:
- ↑ (Up Arrow): Move Forward (North)
- ↓ (Down Arrow): Move Backward (South)
- ← (Left Arrow): Move Left (West)
- → (Right Arrow): Move Right (East)
- ESC: Quit

Run with:
```bash
python interactive_drone.py -v
```

### 2. Automated Flight (`fly.py`)
A pre-programmed drone flight simulation that follows a predefined trajectory stored in `fly_traj.pkl`.

Run with:
```bash
python fly.py -v  # -v flag enables visualization
```

## Technical Details

- The drone model used is the Crazyflie 2.X (`urdf/drones/cf2x.urdf`)
- Base hover RPM is approximately 14468
- Movement is achieved by varying individual rotor RPMs to create directional thrust
- The simulation uses realistic physics including gravity and aerodynamics
- Visualization is optimized for macOS using threaded rendering

## Controls Implementation

The interactive drone uses differential RPM control:
- Forward/Backward movement: Adjusts front/back rotor pairs
- Left/Right movement: Adjusts left/right rotor pairs
- All movements maintain a stable hover while creating directional thrust
- RPM changes are automatically clipped to safe ranges (0-25000 RPM)

Edit: thank you for open-sourcing this project. Really awesome work!

### CODE REVIEW

**Comment by zhouxian** [comment]
Does it work only on macos or cross-platform? if the latter would be great to merge it

**Comment by PieterBecking** [comment]
@zhouxian I think it should work cross-platform (keyboard input with `pynput`), however think it's good to test that before merging. As I'm on macOS, I followed the rendering framework of `examples/render_on_macos.py`.

**Comment by peteryxu** [comment]
nice example.. I copied and posted the code into seperate files. was able to run the fly.py. For the interactive_drone.py, I was able to launch, saw the viewer, but the arrow control did not work for me.  I am on Macbook pro M4.  did not see error in std out. Any insight why this would be the case?

**Comment by YilingQiao** [comment]
Hi Pieter,

Thank you for your great PR!

I tried your code, and it works perfectly. For security reasons, I removed the pickle and embedded the trajectory directly into the code. I also added an argument to support visualization on Linux. Additionally, I formatted the code using Black to ensure it passes CI. Thank you again for your contribution!

I’ve created a PR to your branch. Please try it out and let me know if it causes any issues.

**Comment by PieterBecking** [comment]
@YilingQiao Thank you for the improvement. I like the option of the `mac` flag for platform selection. Works like a charm!

**Comment by PieterBecking** [comment]
@zhouxian Works cross-platform now

**Comment by zhouxian** [comment]
@YilingQiao could you make final approval?

**Comment by YilingQiao** [comment]
@PieterBecking I really appreciate your time and help.
Could you please take a few additional steps:
1. Add an explanation for the -m argument in the README.
2. Use `black examples/drone` to format the code so it can pass the CI.

After those I will merge this PR. Thank you!

**Comment by OIEIEIO** [comment]
Ubuntu 24  -  python interactive_drone.py --vis
[Screencast from 2024-12-22 11-44-36.webm](https://github.com/user-attachments/assets/c44e4298-07c9-4be8-a45f-06ef2f7916e6)

**Pull request merged**
