### PR TITLE
bug: batch reference to links_info

### PR DESCRIPTION
**Pull request by Kashu7100**

### CODE REVIEW

**Comment by zswang666** [comment]
This is handled at PR https://github.com/Genesis-Embodied-AI/Genesis/pull/238

**Comment by Kashu7100** [comment]
Oh, thanks!

**Comment by zhouxian** [comment]
@zswang666 feel free to merge, i think we are good

**Comment by zswang666** [comment]
PR https://github.com/Genesis-Embodied-AI/Genesis/pull/238 merged

**Pull request closed without merging**
